/******************
*Hellojava
*******************
*James Young 
* 1/19/21
*CN 42984, SN C90
*******************/

public class Hello {
	public static void main(String[] args) {
		System.out.println("<James Young>");
		System.out.println("<Hello.java>");
		System.out.println("<Itroductory project>");
		System.out.println("< 1/19/21 >");
		System.out.println("<42984, C90>");
		System.out.println();
	}
}